port: "8000"

db:
  username: "postgres_user"
  host: "localhost"
  port: "3387"
  dbname: "postgres_database"
  sslmode: "disable"
password:
  salt: "aweawddsadfas23423asda"
token:
  signingkey: "qweqsadawqe234324asdas"